cache: .fosstars/project_rating_cache.json
reports:
  - type: markdown
    where: ./
finder:
  repositories:
    - organization: artem-smotrakov
      name: test-rop-one
    - organization: artem-smotrakov
      name: test-rop-two
