name: "Create a report for a project"
description: "The action calculates a security rating for a project and stores it to a branch."
inputs:
  project-scm-url:
    description: "An URL to the project's SCM"
    required: true
    default: "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
  report-branch:
    description: "A branch where the report is stored"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.project-scm-url }}
    - ${{ inputs.report-branch }}
    - ${{ secrets.GITHUB_TOKEN }}
